### ISSUE TITLE
Simple Business On-boarding Flow

### ISSUE THREAD

**Issue by toadzky** [zerobase-io/smart-tracing-api#28]
When a simple business (single-site, no testing) signs up for Zerobase, we need to automatically create the site and it's default QR code and then email the QR code PDF as part of a welcome packet. The other parts of the welcome packet are the FAQ and instructions, as well as a welcome email

See this user story for more information on the requirements for site creation:
https://github.com/zerobase-io/smart-tracing/issues/36

**Comment by ColmByrne** [comment]
Only zip code and email are mandatory at this time

1. Business Name
2. Street address
3. City
4. state (municipality, etc),
5. Postal/zip code
6. Country
7. Contact name/title at business
8. Business type
9. phone number
10. email address

**Comment by miketitchen** [comment]
**Subject line** Welcome to Zerobase
**Email body content**
- https://docs.google.com/document/d/1Io6aaCe-Bq-aH2DowdaY9onj9tJ2RrMxwdCwy-cVbVA/edit

Attachements 
- Zerobase QR.pdf https://docs.google.com/document/d/14FWKc1uyTnCAbqgXflJ8C5F6-UPgSPbKNDju_kgcxwY/edit
- Zerobase Instructions FAQ https://docs.google.com/document/d/1W3Xwr93e3tMw6Zvp1Bsl_X3lajRS3u47iVYgFXOdIEc/edit?usp=sharing

**Comment by miketitchen** [comment]
**Legend**
?: optional fields
**Story**:
Given that I am on the zb home page on mob/pc , when I select register, I am brought to a form to enter:
1. Business Name
2. Street address
3. City
4. state (municipality, etc)
5. Postal/zip code
6. Country
7. Contact name/title at business ?
8. Business type
9. phone number?
10. email address
