### ISSUE TITLE
Invalid Phone Number Exceptions -- difficulty in user formatting numbers to pass in (unclear a good format on both FE and BE side) -- need to add documentation and testing on BE side and add more formatting validation on FE side

### ISSUE THREAD

**Issue by yonglid** [zerobase-io/smart-tracing-api#30]
Add Felipe from BE when he's in the zerobase github

**Comment by toadzky** [comment]
this doesn't seem to be an issue anymore. the front-end is formatting phone numbers correctly. i'm going to close this and label it `wontdo`
